ALTER TABLE users
ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'USER',
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN')),
ADD CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'BANNED'));